# Generated by Django 5.0.3 on 2024-04-10 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='priority',
            field=models.CharField(choices=[('HG', 'Hight'), ('Md', 'Medium'), ('Lw', 'Low')], default='LW', max_length=120),
        ),
        migrations.AlterField(
            model_name='member',
            name='rol',
            field=models.CharField(choices=[('DEV', 'Developer'), ('PO', 'ProductOwner'), ('TL', 'TeamLider'), ('SM', 'ScrumMaster'), ('DBA', 'DataBaseAdministrator')], default='DEV', max_length=60),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projects.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
