# Generated by Django 5.0.3 on 2024-04-17 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_user_completed_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='OwnersTask',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date',
        ),
        migrations.AddField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
    ]
