# Generated by Django 5.0.3 on 2024-04-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_owner_ownerstask_remove_member_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='ownerstasks',
        ),
    ]
