# Generated by Django 5.0.3 on 2024-04-30 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_task_ownerstasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ownerstasks',
        ),
    ]
